/// Flutter icons DiwanIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DiwanIcons
///      fonts:
///       - asset: fonts/DiwanIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DiwanIcons {
  DiwanIcons._();

  static const _kFontFam = 'DiwanIcons';

  static const IconData add = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData announcement = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData back = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData bell = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData chatIcon = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData checkmark = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData clip = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData discover = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData diwan = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData edit = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData forward = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData gallery = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData googleIcon = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData leave = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData menu = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData more = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData movie = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData notification = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData passwordHide = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData passwordShow = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData questionMark = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData searchIcon = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData setting = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData translate = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData twitterIcon = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData url = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe81b, fontFamily: _kFontFam);
}
